<?php
/**
 * Plugin Name:  Status Tracker
 * Plugin URI:   #
 * Description:  Status Tracker.
 * Author:       Wilson
 * Version:      1.0.0
 * Text Domain:  text-domain
 * Domain Path:  /languages/
 * Requires at least: 5.6
 * Requires PHP: 7.4
 * License URI:  https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * License:      GPL v2 or later
 *
 */

 function fsd_page_status_tracker_admin_menu() {
    // Create a new admin page for our app.
    // Includes an empty div with unique ID for React app entry point
    add_menu_page(
        'Status Tracker',
        'Status Tracker',
        'manage_options',
        'status-tracker',
        function () {
            echo '
            <h2>Page Status Tracker</h2>
            <div id="status-tracker"></div> 
        ';
        },
        'dashicons-chart-bar',
        3
    );
}
 
add_action( 'admin_menu', 'fsd_page_status_tracker_admin_menu' );
 
function fsd_load_custom_wp_admin_scripts( $hook ) {
    // Load only on our plugin page - ?page=status-tracker.
    if ( 'toplevel_page_status-tracker' !== $hook ) {
        return;
    }
 
    // Automatically load imported dependencies and assets version - generated by @wordpress/scripts.
    $asset_file = include plugin_dir_path( __FILE__ ) . 'build/index.asset.php';
 
    // Enqueue CSS dependencies.
    foreach ( $asset_file['dependencies'] as $style ) {
        wp_enqueue_style( $style );
    }
 
    // Load our app.js - reference version and dependencies from asset file
    wp_register_script(
        'status-tracker',
        plugins_url( 'build/index.js', __FILE__ ),
        $asset_file['dependencies'],
        $asset_file['version']
    );
    wp_enqueue_script( 'status-tracker' );
 
    wp_localize_script( 'status-tracker', 'localizedData',
		array( 
			'homeUrl' => home_url(),
		)
	);

    // Load our style.css.
    wp_register_style(
        'status-tracker',
        plugins_url( 'assets/css/style.css', __FILE__ ),
        array(),
        $asset_file['version']
    );
    wp_enqueue_style( 'status-tracker' );
}
 
add_action( 'admin_enqueue_scripts', 'fsd_load_custom_wp_admin_scripts' );